### ISSUE TITLE
[Bug] Can't initialize windows workspace under the "Research-GPC" account in Production

### ISSUE THREAD

**Issue by sxinger** [Missouri-BMI/service-workbench-on-aws#17] opened 2021-12-17 17:18 UTC
I am not able to initialize windows workspace under project "Research-GPC-Main-Project", either associating with a study or not: 
![image](https://user-images.githubusercontent.com/19035729/146582113-d9646dca-74fa-4179-b962-af15d8763753.png)

Note that Research-GPC-Main-Project is associated with the external account "Research-GPC" using CFN template following the steps described in: https://github.com/awslabs/service-workbench-on-aws/blob/mainline/docs/Service_Workbench_User_Guide.pdf (page 9). There may be some fundamental healthy issue with either that external account or how the association was made in the first place, given multiple failure incidents recently (related to #15).

**Comment by fergusonsha-umkc** [comment] 2021-12-17 17:38
when we have multiple accounts where SWB is deploying workspaces, like Research-GPC, we have to remember to update all accounts with role policy customizations we make, not just the main account.  I had not added the policy customization that allows the EC2 auto-stop pieces in the template to work, under Research-GPC, and Aaron pointed it out to me.  That's the cause of the newly failing workspace launches against that account.  I've got the policy customization added now, and am testing Windows workspace launch against Research-GPC.

**Comment by fergusonsha-umkc** [comment] 2021-12-17 18:03
Hmm, also looks like I need to update the policy under the Research-GPC account to explicitly allow "cloudwatch:PutMetricAlarm" ... so something differs from how it's working under the primary SWB account too.  We should have tested this under App-Dev against Research-GPC before pushing it into App-Prod :(

**Comment by fergusonsha-umkc** [comment] 2021-12-17 18:25
This may take longer to figure out... still getting this error in the stack despite definitely providing that permission in the role policy...

API: cloudwatch:PutMetricAlarm User: arn:aws:sts::994262031937:assumed-role/prod-oh-umbmi-swb-LaunchConstraint/servicecatalog is not authorized to perform: cloudwatch:PutMetricAlarm on resource: arn:aws:cloudwatch:us-east-2:994262031937:alarm:SC-994262031937-pp-kuallhi75cpxa-IdleCPUAlarm-WI0930LJF9H6 because no identity-based policy allows the cloudwatch:PutMetricAlarm action

**Comment by fergusonsha-umkc** [comment] 2021-12-17 18:35
Double-checking the resource targets on the policy...

**Comment by fergusonsha-umkc** [comment] 2021-12-17 20:27
Discovered the AddCloudWatchAlarm inline policy on the LaunchConstraint role is getting changed back to the one from the Application-Prod account role (i.e. replacing the Research-GPC project ID with the Application-Prod project ID in the resource specifications) every time a workspace launches against Research-GPC, which explains why my corrections weren't taking effect.  I think I know how to work around this, implementing the policy as an attached one, and making sure there is no policy name collision.  Implementing and testing now.

**Comment by fergusonsha-umkc** [comment] 2021-12-17 20:54
Confirmed that because the AddCloudWatchAlarm inline policy name was the same in both the Application-Prod and Research-GPC accounts, when the workspace template launches it was overwriting the policy, so naming it distinctly for the account it is applicable to should fix the issue. Testing again.

**Comment by fergusonsha-umkc** [comment] 2021-12-17 21:22
Well, dangit, that didn't work either.  The separately named inline policy on the role was _removed_ upon workspace launch... it doesn't like that role drift, it feels like.  Hmm.  I will need to think on this and perhaps consult with our AWS-side experts.

**Comment by fergusonsha-umkc** [comment] 2021-12-17 21:25
Should we temporarily remove the Research-GPC project/index from that account, and recreate it against the main account, so that people can continue to launch workspaces without unexpected errors (from their perspective), in the meantime? @sxinger

**Comment by fergusonsha-umkc** [comment] 2021-12-17 21:52
Wait, possible eureka...

**Comment by fergusonsha-umkc** [comment] 2021-12-17 22:14
FIXED IT!

Made the requisite policy change to include the Research-GPC account, on the inline policy for the LaunchConstraint role under Application-Prod, and it carried over into the role under Research-GPC this time 😊

**Comment by sxinger** [comment] 2021-12-20 21:15
There are only two studies under Research-GPC account: GROUSE-MUIRB2057285-Obesity , GROUSE-MUIRB2057285-ALS (both with me involved). I tested it out by creating a workspace under each study and did the following usability tests: 
- saving data to S3 bucket - worked
- snowflake db connectivity - worked
- same workspace associated with multiple studies - worked
- getting data from S3 bucket - worked

@fergusonsha-umkc one little caveat I noticed was that, does rclone only sync once at workspace creation? If I manually upload something into the corresponding S3 study-data bucket, it doesn't sync right way or even after I stop and re-start the workspace: 
![image](https://user-images.githubusercontent.com/19035729/146833426-3b39d5cd-c828-4ca4-aad9-2d09fcd4cc6c.png)
But if I create a brand new workspace, the uploaded file is synced. 

PS: Please don't change the original class of the issue (i.e., Bug, Feature, or Misc). Closing it with comment would suggest fixing of the issue.

**Comment by fergusonsha-umkc** [comment] 2021-12-20 21:28
That's not an rclone workspace, it's an s3-synchronizer workspace.  Rclone is only fully implemented in dev still, while we stress test it. 

I wasn't able to change the status of this bug-fix to "In Validation," like I am able to with other issues, thus I updated the title to indicate original problem resolution and was monitoring it before closure.  I left the original class of the issue intact, as Bug, and removed only the "Urgent" status, as it was no longer so.

**Comment by fergusonsha-umkc** [comment] 2021-12-20 21:29
I can tell it's not an rclone workspace because D: is showing itself as a physical disk in the File Explorer, and does not have the study label, FYI.

**Comment by fergusonsha-umkc** [comment] 2021-12-20 21:45
Since the workspace launching against Research-GPC is fixed, I'm closing this issue.

**Closed as completed by fergusonsha-umkc** 2021-12-20 21:45 UTC
Labels: bug
