### ISSUE TITLE
[Feature Request] SWB upgrade in Dev/Sandbox env

### ISSUE THREAD

**Issue by sxinger** [Missouri-BMI/service-workbench-on-aws#14] opened 2021-12-02 19:11 UTC
We will want to test out the upgrade SWB version (with TRE and R-server workspace) under Dev/Sandbox environment to prep for the upgrade in production

**Comment by fergusonsha-umkc** [comment] 2021-12-02 19:14
I'll be able to begin working on deployment of this under Sandbox, this coming Monday :)

**Comment by fergusonsha-umkc** [comment] 2021-12-20 19:55
Pushing this to January, due to other commitments this week with UMKC ISFS projects

**Comment by fergusonsha-umkc** [comment] 2021-12-20 21:48
This is a duplicate of #10 so closing it and copying updates to there

**Comment by sxinger** [comment] 2022-01-10 17:19
@fergusonsha-umkc this is not a duplicate. #10 is the root ticket laying out the entire plan of performing the upgrade (assigned to me to oversee), this is one of the specific task of just testing the upgrade out in Sandbox.

**Comment by sxinger** [comment] 2022-01-19 19:20
@fergusonsha-umkc  any updates on this?

**Comment by fergusonsha-umkc** [comment] 2022-01-19 19:23
Not yet.

**Comment by sxinger** [comment] 2022-01-27 21:59
@fergusonsha-umkc any updates on this?

**Comment by fergusonsha-umkc** [comment] 2022-01-28 15:57
As soon as I am able to focus on this, and it will need dedicated focus not multitasking, I will.  There are start-of-semester obligations I have to fulfill for UMKC, before I can switch mental gears back here.  I'll provide updates, once I have something, meanwhile please trust that it's not been forgotten as a priority.

**Comment by sxinger** [comment] 2022-01-28 16:00
Given @aaronmbruce's 100% commitment to this project, would it be possible for him to take a lead on this task? @vasanthi014 Please work with aaron and shaun to load-balance on this task.

**Comment by fergusonsha-umkc** [comment] 2022-01-28 16:06
He has no prior experience with deploying Service Workbench from its Git codebase, however he will be involved.  Our plan has been to have me do Sandbox and work through any wrinkles, then I will guide him with doing it hands-on himself in Dev, to get the experience.

**Comment by fergusonsha-umkc** [comment] 2022-01-28 17:12
I aim to start working on Sandbox upgrade and switch to TRE, this coming Monday.

**Comment by fergusonsha-umkc** [comment] 2022-01-31 17:46
Deploying Cloud9 environment for Sandbox SWB upgrade

**Comment by fergusonsha-umkc** [comment] 2022-01-31 18:48
Codebase pulled to latest release, looking for the most recent upgrade documentation to avoid assumptions.

**Comment by fergusonsha-umkc** [comment] 2022-01-31 19:12
Using https://github.com/awslabs/service-workbench-on-aws/blob/mainline/docs/Service_Workbench_Installation_Guide.pdf

**Comment by fergusonsha-umkc** [comment] 2022-01-31 20:18
C9 install source updated to latest 4.x release, verified config files are still set, running the environment deploy script per upgrade instructions ...

**Comment by fergusonsha-umkc** [comment] 2022-01-31 20:28
----- ENVIRONMENT DEPLOYED SUCCESSFULLY 🎉 -----
 
 Doing post-upgrade CFN steps

**Comment by fergusonsha-umkc** [comment] 2022-01-31 20:35
The new ALB RStudio Server instructions are rather more involved than just rebuilding a new AMI, looks like.  Dedicated section for it.

**Comment by fergusonsha-umkc** [comment] 2022-01-31 20:58
40 changes including addition of AppStream components, being made to the 'umbmiaws-swb-onboard-account' stack as part of the upgrade

**Comment by fergusonsha-umkc** [comment] 2022-01-31 20:59
Hmm, stack update failed... troubleshooting

**Comment by fergusonsha-umkc** [comment] 2022-01-31 21:02
Reason for failure:
<html>
<body>


2022-01-31 14:57:33 UTC-0600 | AppStreamStack | CREATE_FAILED | null (Service: AmazonAppStream; Status Code: 400; Error Code: AccessDeniedException; Request ID: 14ec11eb-14fd-4c44-8837-45ca35ff7673; Proxy: null)
-- | -- | -- | --



</body>
</html>

**Comment by fergusonsha-umkc** [comment] 2022-01-31 21:03
Going to AppStream and seeing if it has to be enabled first, maybe

**Comment by fergusonsha-umkc** [comment] 2022-01-31 21:21
Oh, crud...

Region Unsupported
AppStream 2.0 is not available in US East (Ohio). Please select another region.

So.... hmm.  I will ping Travis and Nathan about when AppStream will be supported in our region, and ask for ideas on how we can disable it in the meantime to at least have the rest of the upgrade to play with...

**Comment by fergusonsha-umkc** [comment] 2022-01-31 21:39
Email sent:
--
Hi Travis, Nathan,

I was working on upgrading SWB in our Sandbox environment today, and everything was going pretty smoothly until I tried the onboard account stack update, which failed out when attempting the AppStream stages.  When I went to AppStream directly in our AWS console, to see if maybe it needed to be activated/enabled for the account, I was presented with this rather dismaying message:

Region Unsupported
AppStream 2.0 is not available in US East (Ohio). Please select another region.

Is there any way to get an ETA on when AppStream will become available in our region so we can use the Trusted Research Environment feature, and in the meantime, can we toggle it off in order to take advantage of the rest of the upgrade's features and bug-fixes?  If we need to hop on a Zoom session to discuss, we can arrange that.

Thank you!

**Comment by fergusonsha-umkc** [comment] 2022-01-31 22:00
Travis responded:

Let me get with the service team and ask about AppStream in us-east-2.

As far as TRE goes, that feature is a one-way door once it’s fully deployed.  (In other words, once you turn it on, you cannot turn it off.)  If it wasn’t completed, you can try setting things to false in the configuration document and re-deploy.

**Comment by fergusonsha-umkc** [comment] 2022-01-31 22:01
I'll attempt his suggestion about turning it off, tomorrow.

**Comment by fergusonsha-umkc** [comment] 2022-02-03 16:33
Re-running the stack update with AppStream disabled

**Comment by fergusonsha-umkc** [comment] 2022-02-03 16:38
Stack update was successful with AppStream disabled, working on getting logged in to test it out.  Login page, for Sandbox at least, has changed a bit.  My AWS SSO isn't working, but I don't remember if we fully implemented that in Sandbox, maybe just in Dev.

**Comment by fergusonsha-umkc** [comment] 2022-02-03 16:58
OK, got logged in as root@example.com using Cognito Native Pool, and it does look like we have AWSSO accounts set up, so I will need to debug why those aren't working now...

**Comment by fergusonsha-umkc** [comment] 2022-02-03 17:24
Also need to do the AMI rebuilds...

**Comment by fergusonsha-umkc** [comment] 2022-02-03 17:31
I'm going to back-port our configurations and customizations from Dev to Sandbox, which should fix some things like SSO...

**Comment by fergusonsha-umkc** [comment] 2022-02-03 18:26
OK, had to reassign the IdP::UserPool attributes to get SSO working again.  Whew!

**Comment by fergusonsha-umkc** [comment] 2022-02-03 19:16
Also having to repopulate the VpcId and SubnetId in the machine-images/config/infra/*.json , since we don't have a designated default VPC

**Comment by fergusonsha-umkc** [comment] 2022-02-03 19:32
Removed old stock AMIs/Snapshots and building upgraded machine images for Linux, Windows, EMR ... RStudio is handled separately

**Comment by fergusonsha-umkc** [comment] 2022-02-03 19:53
Update from Travis:
"As for AppStream, it looks like it is in private beta for us-east-2.  The team didn’t have a target date yet, but they do have some customers who are using it.  If this is something you would like to pursue, we would need to get an NDA in place with you and then we could invite you into the private beta, as well.  So, think about that one for a while and let me know what you would like to do, if anything."

**Comment by fergusonsha-umkc** [comment] 2022-02-03 20:04
To expedite things, I will just set up one configuration for each workspace type under Sandbox, which we can adjust instance type for, as desired.  When we do Dev, we'll align it with how Prod is set up.

**Comment by fergusonsha-umkc** [comment] 2022-02-03 20:06
![image](https://user-images.githubusercontent.com/81329060/152420370-9a569669-876f-4c7a-abfb-62732c683a62.png)

Nice!  Given this, I might hold up a bit on importing workspaces until we get AppStream turned on :)

**Comment by fergusonsha-umkc** [comment] 2022-02-03 20:08
I will import Sagemaker at least, as it doesn't use an EC2 instance

**Comment by fergusonsha-umkc** [comment] 2022-02-03 20:11
Nice, the template variables are pre-populated now :)

**Comment by fergusonsha-umkc** [comment] 2022-02-03 22:12
Travis update:
"Let me get back to the service team and ask what the process is for the private beta.  It’s usually just a matter of knowing what account to add to an allow-list.  I didn’t realize you had the NDA in place already.  (Thanks, Matt!)  I will get back with you soon."

**Comment by fergusonsha-umkc** [comment] 2022-02-04 19:44
Sagemaker workspace tested successfully

**Comment by fergusonsha-umkc** [comment] 2022-02-04 20:08
Error provisioning environment shaun-test-upgraded-Linux. Reason: AmazonCloudFormationException Parameters: [EgressStoreIamPolicyDocument, SolutionNamespace, IsAppStreamEnabled] do not exist in the template (Service: AmazonCloudFormation; Status Code: 400; Error Code: ValidationError; Request ID: 4c0459f7-72c9-49df-b6af-56c52f7d622f; Proxy: null)

So I will wait until we have AppStream available to proceed with the rest of this.

**Comment by fergusonsha-umkc** [comment] 2022-02-21 15:45
Travis update:  "Your accounts have been added to the allow-list.  You should be good to use AppStream in the us-east-2 region in those accounts.  Deploy away!"

I will resume this soon as I can.

**Comment by vasanthi014** [comment] 2022-02-24 21:11
@fergusonsha-umkc Let's request a demo presentation from Travis regarding AppStream

**Comment by fergusonsha-umkc** [comment] 2022-02-24 21:50
Current status of implementing TRE in Sandbox:
Hey Travis, I eventually found the AppStream documentation (its not part of the Installation Guide PDF yet, looks like) under docs/docs/post_deployment/appstream.md and its helped get me further along on enabling this, but not by much unfortunately, I'm already running into a problem again... we might need to set up a working session in Zoom sometime in the coming week to go through this in realtime?

When running the commands to kick off the AppStream Image Builder, I ran into this problem (maybe because we don't have a default VPC defined in our accounts, which I had to define in the AMI image .json files for those to build, but its not as clear to me how to do that in this .js file)...


> AWSReservedSSO_AWSAdministratorAccess_8d0d41bd23adb7bf:~/environment/service-workbench-on-aws/scripts/app-stream (mainline) $ npm run start-image-builder -- default us-east-2 default default

> app-stream-scripts@1.0.0 start-image-builder
> node -e "require('./start-image-builder.js').runCodeAsScript()" "default" "us-east-2" "default" "default"
> Starting Image Builder using AWS Profile default in region us-east-2 with base image AppStream-WinServer2019-10-08-2021 and instance type stream.standard.medium
> Starting image builder with name SWBImageBuilder-1645723647265
> ** Failed to start image builder TypeError: Cannot read properties of undefined (reading 'VpcId')**
>    at StartImageBuilder.createImageBuilder (/home/ec2-user/environment/service-workbench-on-aws/scripts/app-stream/start-image-builder.js:63:42)
>    at processTicksAndRejections (node:internal/process/task_queues:96:5)
>    at async StartImageBuilder.run (/home/ec2-user/environment/service-workbench-on-aws/scripts/app-stream/start-image-builder.js:37:7)

I will continue to troubleshoot it while waiting for a response, too.

**Comment by fergusonsha-umkc** [comment] 2022-02-28 17:12
Hard-coding the VpcId worked to get image builder kicked off:

> npm run start-image-builder -- default us-east-2 default default 
> app-stream-scripts@1.0.0 start-image-builder
> node -e "require('./start-image-builder.js').runCodeAsScript()" "default" "us-east-2" "default" "default"
> Starting Image Builder using AWS Profile default in region us-east-2 with base image AppStream-> WinServer2019-10-08-2021 and instance type stream.standard.medium
> Starting image builder with name SWBImageBuilder-1646068218369
> Waiting for Image Builder to finish starting up. This can take 5 to 10 minutes
> Image Builder is in PENDING state

**Comment by fergusonsha-umkc** [comment] 2022-03-02 17:25
**Status update,** after encountering lots of contradictory and just plain not-working scenarios with the Sandbox upgrade yesterday:  I've backed the git source tree down to v4.3.1 which is latest release of version 4, and did more of a clean-slate install to ensure all the components are in sync with this version release, and today things are looking better... although I do hope to be able to do an upgrade path in the App-Dev environment, following their directions did not work as described/expected for Sandbox :(  I am documenting anything that I've had to do that varies from their documentation, particularly regarding VPCs.  I believe our templates and AMIs will remain functional, though we may have to add an AppStream component to them.  I'll have more information after I get a successful workspace launch under AppStream in Sandbox...

**Comment by fergusonsha-umkc** [comment] 2022-03-02 18:24
Got a Linux workspace launched under Sandbox SWB v4.3.1 and connected through AppStream, aka the Trusted Research Environment.  I will admit, for as much as we fought to get AppStream, I am wholly underwhelmed by the user experience.  You'll see what I mean.  I'm doing iterative testing of all workspace types, and then will open Sandbox for general testing very soon.

**Comment by sxinger** [comment] 2022-03-02 18:46
> Got a Linux workspace launched under Sandbox SWB v4.3.1 and connected through AppStream, aka the Trusted Research Environment. I will admit, for as much as we fought to get AppStream, I am wholly underwhelmed by the user experience. You'll see what I mean. I'm doing iterative testing of all workspace types, and then will open Sandbox for general testing very soon.

That will be some good feedback to the Travis and AWS SWB team. Also, if the user experience is compromised too much, I think we can probably wait until an improved release is ready, or just deploy it partially for more sensitive data. Can't wait to test it out and criticize, lol

**Comment by fergusonsha-umkc** [comment] 2022-03-02 20:21
OK the Windows workspace connection experience is MUCH better than the Linux one was.

**Comment by fergusonsha-umkc** [comment] 2022-03-02 20:55
I'll open this for testing once I'm sure all the workspace types launch without issue, and know how to go through the connection hoops for each of them myself, but I'm not calling this "done" done until I get the RStudio piece set up, which is a saga in and of itself in the installation guide now.

**Comment by fergusonsha-umkc** [comment] 2022-03-09 17:26
All workspaces marked Approved are working in the Trusted Research Environment under Sandbox SWB now.  I'm opening access to Aaron as admin, and Song, Vasanthi as researchers.  This will let you get a feel for the new way workspaces are connected to via AppStream instances, while I continue work on installing the new RStudio backend and instance.  EMR is proving difficult to get launched also, because none of the instance types I set up are acceptable to it, despite being in the valid list for some reason.  I figured RStudio is more important to focus on though.

Please remember this is a fresh-out-of-the-box instance of SWB for Sandbox to get experience with what it entails, our own customizations will be applied when we upgrade App-Dev after all baseline components are vetted in Sandbox.

EDIT: @vasanthi014 this was the note I had mentioned testing everything but Rstudio in the meantime, but I forgot to use at's :(

**Comment by fergusonsha-umkc** [comment] 2022-03-09 17:26
I'm also looking into how to simplify the login jump page for Service Workbench so AWSSSO is the only (or default) option, although you can use SSO either path you pick, the Cognito path just has the potential for confusion I think.  They integrated Cognito into the Service Workbench deployment script, and are deprecating the DynamoDB-based user logins in favor of Cognito for those who don't have SSO set up.  Our landing page has customization in App-Dev/App-Prod for the usage agreement also, so not a big deal.

**Comment by fergusonsha-umkc** [comment] 2022-03-23 16:10
Progress report:  got through my first pass at the RStudio-Server instructions, resulting in an AMI and stack which I am currently testing in SWB under Sandbox

**Comment by fergusonsha-umkc** [comment] 2022-03-23 19:05
Well, the first ACM certificate I set up couldn't be validated, I think because I had an extra character in the corresponding CNAME value.  Generated a new one, double-checked the CNAME value matches without that extra character, and just waiting for it to come out of Pending status, so the workspace stack will launch past that point (it failed due to the certificate not being valid)

**Comment by fergusonsha-umkc** [comment] 2022-03-29 14:28
Getting the hosted domain certificate to validate via DNS is the last hurdle before being able to test the new RStudio Server workspace... although once I get it working in a public hosted zone, I'd like to make it work in a private hosted zone, in keeping with the TRE model.

**Comment by fergusonsha-umkc** [comment] 2022-04-07 20:42
We met with Nathan this morning but still couldn't determine why Certificate Manager isn't DNS validating the certificate we need, so upon his advice I am going to enter a ticket through DLT support for Amazon's ACM team to look into it with us.  All our own testing seems to show that the ACM DNS validation service _should_ be able to get a CNAME response from our hosted zone records for its validation check, but, there also may have been a missing step in the RStudio ALB deployment documentation (a lot of fundamental assumptions get made in their documentation that don't all apply in our Control Tower governed organization structure situation).  Meanwhile, all of the rest of the SWB 4.x upgrade is ready to be tested out, which Vasanthi said she would do perhaps with some student workers.  My recommendation would be for us to proceed with the upgrade in our Dev environment, to prepare for a production upgrade and test with our custom assets, and get the RStudio component in place as soon as this one issue is solved.

Also, Nathan mentioned, he and/or Travis will be reaching out to us soon regarding the _next_ next version of SWB which apparently has an even bigger paradigm shift involved in how it would operate... I am trying to get more details.

**Comment by fergusonsha-umkc** [comment] 2022-04-08 17:44
DLT got in touch with me, and I've reached out via email for approval to upgrade support tiers or seek alternative avenues:

Shaun, thanks again for taking my call.
 
As we discussed, upon review of account 375678937566, this account currently has a Basic Support Plan associated with it, which unfortunately doesn't have access to the Technical Support option needed to pursue engagement with the AWS Technical Support team.
 
Furthermore, as an Internet2 organization you have control over your support levels at any given time, if you would like to continue this ticket with the AWS Technical Support backline team you may upgrade your support plan to the Business Level Plan (which you can always change back to Basic if you choose to do so)
 
You mentioned that you will need to discuss this with your colleague's, so we will be on standby for your  feedback on how to proceed
 
 
Respectfully,
Michael Davis
DLT Confirmed Stateside Support

**Comment by fergusonsha-umkc** [comment] 2022-04-11 15:11
Nathan got some feedback from the ACM team that proved key to understanding what's going on.  We had not registered the domain under which the certificates were being created, yet, due to some Service Workbench deployment instruction gaps, but we have the nextgenbmi.umsystem.edu domain that we will use.  Based on the documentation, it seemed like this would be an internal-only DNS domain managed by Route53's Hosted Zone, but it needs to be an actual registered Internet domain (in hindsight, obvious).  So I will proceed with working with DoIT to get the necessary pieces registered with them before creating the hosted zone in Sandbox.  I've deleted the prior-created hosted zone and certificate until then.

**Comment by fergusonsha-umkc** [comment] 2022-04-12 15:57
Service Request 1079808 has been created for CNAME creation to validate the ACM certificate using the nextgenbmi.umsystem.edu domain

**Comment by fergusonsha-umkc** [comment] 2022-04-12 16:28
Quick response!
![image](https://user-images.githubusercontent.com/81329060/163009940-5e04a49f-5691-468a-bbf5-d69fa959f97c.png)

**Comment by fergusonsha-umkc** [comment] 2022-04-12 16:28
I will proceed this week on testing and tuning the RStudio workspace, and next week I believe Aaron and I can begin doing the upgrade in our App-Dev environment to introduce our customizations... I might, however, introduce our customizations into Sandbox first and get things all worked out there, so we still have App-Dev available for any "needs testing before production implementation" in our current environment.  Then when we are able to have a maintenance window of 2-3 days, we can upgrade our dev and prod instances.

**Comment by fergusonsha-umkc** [comment] 2022-04-15 15:30
Apparently the entire SWB instance needs to have a custom domain name in order for the RStudio Server workspace to launch, so I'm getting sandbox.nextgenbmi.umsystem.edu registered and certified, and will redeploy using that, and cross all my fingers.

**Comment by fergusonsha-umkc** [comment] 2022-04-27 15:29
The new custom domainname of sandbox.nextgenbmi.umsystem.edu is now set up and working, hopefully this will do the trick for RStudio Server to be happy.  I fixed the Cognito and SSO application integrations to use this, and now they are happy.

**Comment by sxinger** [comment] 2022-04-27 19:01
Testing Report: 04/27/2022

1. Onboarding message and do we need to keep the "Cognito native pool" option? 
![image](https://user-images.githubusercontent.com/19035729/165589131-3f5eed06-9d80-4ef1-bfcb-04b7815fd793.png)

2. Sagemaker workspace via AppStream 2.0
- longer waiting time at every launch (not just the initial time)
![image](https://user-images.githubusercontent.com/19035729/165590827-bdbe46e9-ffe7-47f0-b2e1-efcce3e34159.png)
- freezes a lot (try `pip list`)
- can't do `pip install`

**Comment by vasanthi014** [comment] 2022-04-27 19:12
@sxinger It would be great if we can track the testing in a separate ticket. I created this ticket for you https://github.com/Missouri-BMI/service-workbench-on-aws/issues/22

**Comment by vasanthi014** [comment] 2022-05-05 20:41
Next steps: @sxinger will reach out to Travis and setup accounts for Travis/Natan in our Sandbox environment.

**Comment by vyshu1094** [comment] 2022-05-19 20:30
We have decided the next steps with Travis and Nathan. Follow up tickets have created.

**Closed as completed by vyshu1094** 2022-05-19 20:30 UTC
Labels: enhancement, HIGH
