### ISSUE TITLE
SWB access to Huzifa and create new SWB project 'Outback-Analytics'

### ISSUE THREAD

**Issue by vasanthi014** [Missouri-BMI/service-workbench-on-aws#41] opened 2023-04-05 19:07 UTC
Please create AWS account and give Huzaifa access to service workbench.

@ghkkhan

**Comment by vasanthi014** [comment] 2023-04-05 19:09
@fergusonsha-umkc Can you please share list of all SWB projects so that I can determine which group will be more appropriate for him.

**Comment by fergusonsha-umkc** [comment] 2023-04-05 19:26
Sent in Teams :)

**Comment by vasanthi014** [comment] 2023-04-05 20:41
Let's create a new project in swb. 

ID : Outback-Analytics 
Description: For NextGenBMI engineers and students to perform analytics on outback data

**Comment by vasanthi014** [comment] 2023-04-05 20:43
@ghkkhan what softwares would you be using in the workspace for your analytics?

**Comment by fergusonsha-umkc** [comment] 2023-04-06 14:22
@aaronmbruce would you please take care of the user and index/project setup today?  Link the project to the main account.  Appreciate it :)

**Comment by ghkkhan** [comment] 2023-04-06 15:09
For now, I'll just need to use Python to test out the code that Will has written. It should also be able to run SQL queries to Snowflake.

**Comment by aaronmbruce** [comment] 2023-04-06 17:56
Huzaifa already has an account, I resent the verification and password setup emails.

**Comment by aaronmbruce** [comment] 2023-04-06 17:58
I have created a new project and index, should I also create a new study?

**Comment by vasanthi014** [comment] 2023-04-07 02:57
> I have created a new project and index, should I also create a new study?

Yes. How is a project related to a study?

**Comment by fergusonsha-umkc** [comment] 2023-04-07 14:02
A study is linked to a project, but not necessary to use the project.  A study is for storing files that need to be accessible across many workspaces.  If you already have a study they will be using, a new one is not strictly necessary.

**Comment by ghkkhan** [comment] 2023-04-10 17:50
@aaronmbruce - Hi! Sorry to bug you again. I reset my password on Friday and tried to log in over the weekend to set up the instance, but I could not. I think I may have incorrectly noted down the wrong password. 

Can you send me another password reset link?
Thanks

**Comment by aaronmbruce** [comment] 2023-04-10 19:45
@ghkkhan sent

**Comment by ghkkhan** [comment] 2023-04-11 17:22
@aaronmbruce Hey, i accidentally archived the reset-link you sent me and didn't find it until after it expired.
I'm so sorry for this but can you send it to me again? I'll jump on it and get it done right away this time.

**Comment by aaronmbruce** [comment] 2023-04-12 16:47
@ghkkhan no sweat, sent again

**Comment by ghkkhan** [comment] 2023-04-12 17:55
@aaronmbruce OK I was able to reset the password, but for some reason, I still can't login. I'm sure I saved the password properly this time so maybe the issue is with the username? It is "hkg8b@umsystem.edu", right?

**Comment by ghkkhan** [comment] 2023-04-12 17:57
@aaronmbruce Actually, disregard. I was using the wrong login link. 
I'm in the system now. Thanks a lot for your help

**Comment by fergusonsha-umkc** [comment] 2023-04-19 17:43
Please close this out if all is well now :)

**Closed as completed** 2023-04-19 19:06 UTC
Labels: validation
